name: bivme312
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas=2.2.2
  - pyvista=0.44.1
  - plotly=5.22.0
  - scipy=1.13.1
  - moviepy=1.0.3
  - cvxopt=1.3.0
  - nltk=3.8.1
  - numpy=1.26.4
  - numpy-stl=3.1.1
  - rich=13.7.1
