name: bivme312
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - contourpy=1.2.0
  - cvxopt=1.3.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - decorator=5.1.1
  - double-conversion=3.1.5
  - dsdp=5.8
  - eigen=3.4.0
  - expat=2.6.2
  - ffmpeg=4.2.2
  - fftw=3.3.9
  - fontconfig=2.14.2
  - fonttools=4.51.0
  - freetype=2.12.1
  - gl2ps=1.4.2
  - glew=2.2.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - glpk=4.65
  - gmp=6.2.1
  - gnutls=3.6.15
  - gsl=2.7.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - imageio=2.33.1
  - imageio-ffmpeg=0.5.1
  - joblib=1.4.2
  - jpeg=9e
  - jsoncpp=1.9.4
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.7.1
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libglu=9.0.0
  - libgomp=14.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.17
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libvpx=1.7.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libzip=1.8.0
  - libzlib=1.2.13
  - loguru=0.5.3
  - lz4-c=1.9.4
  - matplotlib-base=3.8.4
  - metis=5.1.0
  - moviepy=1.0.3
  - mpfr=4.0.2
  - mysql=5.7.24
  - ncurses=6.4
  - nettle=3.7.3
  - nltk=3.8.1
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpy-stl=3.1.1
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - pcre2=10.42
  - pillow=10.4.0
  - pip=24.0
  - platformdirs=3.10.0
  - plotly=5.22.0
  - pooch=1.7.0
  - proglog=0.1.9
  - proj=6.2.1
  - pybind11-abi=5
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python-utils=3.3.3
  - python_abi=3.12
  - pytz=2024.1
  - pyvista=0.44.1
  - qt=5.15.9
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - readline=8.2
  - regex=2023.10.3
  - requests=2.32.3
  - scipy=1.13.1
  - scooby=0.10.0
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - suitesparse=5.10.1
  - tbb=2021.8.0
  - tenacity=8.2.3
  - tk=8.6.14
  - tqdm=4.66.4
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - utfcpp=3.2.1
  - vtk=9.0.3
  - wheel=0.43.0
  - x264=1!157.20191217
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - pygments==2.18.0
      - rich==13.7.1