name: Tests

#on:
#  - push
#  - pull_request

on:
  push:
    branches:
      - "10-setup-up-continuous-test-automation-with-github-actions"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/tests.yml"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox